lightninglabs/docs.lightning.engineering

- .github/workflows/doc-sync.yaml
This commit updates our doc sync to pull all docs from other LL repos into `docs/{repo name}`. It also adds loop, pool and faraday docs, which were previously excluded because we didn't have place to put them. 
While testing this out locally, I noticed that the PR and merge GH action has a race when multiple PRs are made at the same time, and may fail because "master branch has changed". Since we run regular syncs, it's acceptable for the occasional failure (we can also always manually rerun if we need the sync immediately).
> workflow: sync all docs to single dir and add loop/pool/faraday

- .github/CODEOWNERS
This PR adds codeowners for our main dirs. 
PRs that touch the dir you're assigned to will immediately assign you as a reviewer. This got quite noisy in the lnd repo, but I think is worth adding as we start out with docs at least so that we ensure contributor PRs get reviewed and people aren't discouraged because they fall through the cracks. 
Requesting review from everybody included, comment on the PR if you don't want to be included/ would like another allocation.
> github: add codeowners for main directories

- .github/workflows/doc-sync.yaml
Use a generic github user for the author of our update commits.
The default for this action is to use the creator of the action, which makes it look like I'm padding my GH with a bot :')
> workflows: set github user for actions commit

- .github/workflows/doc-sync.yaml
If there are changes in multiple repos, the merge action can
fail because its view of master gets out of date.
Tested this out on my [fork](https://github.com/carlaKC/docs.lightning.engineering/actions/runs/689738184) - jobs ran in order and succeeded when 2x repos needed changes. 
> workflows: run single doc-sync at a time

- lightning-network-tools/lnd/payments.md
I assume this line is trying to state that keysend is experimental
> Fixed typo

- lightning-network-tools/lightning-terminal/get-lit/macos-remote-mode.md
Closes #135 
Updated bad option keys, and added the global `network` flag. Also added correct escaping to macOS file paths, so the text can be copied into a terminal.
> Update remote macOS Lit docs

- lightning-network-tools/lnd/get-started-with-lnd.md
> Update text around giving LND access to bitcoind RPC

- lightning-network-tools/lnd/migrating-lnd.md
More commits may be added here as I am reading through [`migrating-lnd`](https://docs.lightning.engineering/lightning-network-tools/lnd/migrating-lnd).
> migrating-lnd.md: serverl typo

- lapps/guides/add-features/display-node-alias-and-balance.md
> fix typo in display-node-alias-and-balance.md

- .gitattributes
Before this change, repository gets detected as:
Shell 100.0%
After this change, repository gets detected as:
Markdown 99.9%
Shell 0.1%
This change was added for a cosmetic effect on GitHub. It might be
good to go away once this repository is no longer hosted at GitHub, or
if GitHub ceases to use the line, or GitHub ceases to exist.
---
> Make Markdown linguist-detectable

- lightning-network-tools/taro/first-steps.md
This part has two errors in it:
- There is only one dash
- It's a boolean flag, so it cannot be set to false with the CLI library that we use (just omitting the flag will set the value to false)
Also, emission is currently not working.
> taro: remove incorrect --enable_emission flag

- the-lightning-network/taro/taro-protocol.md
> Taro fixes

- the-lightning-network/overview.md
Fix the broken link.  It seems like it should link to `The Gossip Network` page.
> Update broken link

- the-lightning-network/multihop-payments/timelocks.md
Changed "CTLV to CLTV" and "Check-TIMELOCK verify" to "Check-LOCKTIME verify".
> Fixed Typos (CTLV --> CLTV)

- build-a-lapp/connect-to-lnd/display-node-alias-and-balance.md
> Fix Typo in `Display Node Alias and Balance`

- lightning-network-tools/taproot-assets/get-tapd.md
> fix typo in the command of `tapd`

- lightning-network-tools/loop/autoloop.md
> update autoloop guide manually

- .github/workflows/doc-sync.yaml
Also sync the `docs/` folder from the [Taproot Assets repository](https://github.com/lightninglabs/taproot-assets/tree/main/docs).
> GitHub: sync taproot-assets docs

- docs/faraday/accounting.md
**Description:**
This pull request addresses a minor but important typo in the documentation. The word "Bitcon" has been corrected to "Bitcoin" in the **Bitcoin Backend** section. 
**Fix:**
- Corrected the typo "Bitcon" to "Bitcoin" in the sentence:
> "It is strongly recommended that Faraday is run with a connection to a **Bitcon** node..."
**Importance:**
This is a minor correction, but it's important for accuracy and clarity. "Bitcoin" is the proper name of the blockchain, and leaving the typo "Bitcon" could cause confusion for readers, especially for those unfamiliar with the system. Ensuring proper spelling is crucial for maintaining the professionalism and credibility of the documentation.
synced from upstream repositories …
> Typo Update accounting.md

- lightning-network-tools/taproot-assets/rfq.md
This PR adds some brief clarity on how RFQ messages are actually exchanged.
> add clarity on how RFQ messaging actually happens

- lightning-network-tools/taproot-assets/universes.md
more tweaks of yesterday's changes
> further clarify federations and the default universe
